stages:
  - stage:
    displayName: "build & test"
    jobs:
      - job: Windows
        pool:
          name: Hosted VS2017
          demands: npm
        steps:
          - task: NodeTool@0
            displayName: 'Use Node 8.x'
            inputs:
              versionSpec: 8.x
          - task: Npm@1
            displayName: 'Install dependencies'
            inputs:
              verbose: false
          - task: Npm@1
            displayName: 'Compile sources'
            inputs:
              command: custom
              verbose: false
              customCommand: 'run compile'
          - script: 'node node_modules/vscode/bin/test'
            displayName: 'Run tests'
          # Publish Code Coverage Results
          # Publish Cobertura or JaCoCo code coverage results from a build
          - task: PublishCodeCoverageResults@1
            inputs:
              codeCoverageTool: 'cobertura' # Options: cobertura, jaCoCo
              summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml
              #reportDirectory: # Optional
              #additionalCodeCoverageFiles: # Optional
              #failIfCoverageEmpty: false # Optional
      - job: macOS
        pool:
          name: Hosted macOS
          demands: npm
        steps:
          - task: NodeTool@0
            displayName: 'Use Node 8.x'
            inputs:
              versionSpec: 8.x
          - task: Npm@1
            displayName: 'Install dependencies'
            inputs:
              verbose: false
          - task: Npm@1
            displayName: 'Compile sources'
            inputs:
              command: custom
              verbose: false
              customCommand: 'run compile'
          - script: 'node node_modules/vscode/bin/test'
            displayName: 'Run tests'
          - task: PublishCodeCoverageResults@1
            inputs:
              codeCoverageTool: 'cobertura' # Options: cobertura, jaCoCo
              summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml
      - job: Linux
        pool:
          name: Hosted Ubuntu 1604
          demands: npm
        steps:
          - task: NodeTool@0
            displayName: 'Use Node 8.x'
            inputs:
              versionSpec: 8.x
          - task: Npm@1
            displayName: 'Install dependencies'
            inputs:
              verbose: false
          - task: Npm@1
            displayName: 'Compile sources'
            inputs:
              command: custom
              verbose: false
              customCommand: 'run compile'
          - script: |
              set -e
              /usr/bin/Xvfb :10 -ac >> /tmp/Xvfb.out 2>&1 &
              disown -ar
            displayName: 'Start xvfb'
          - script: 'node node_modules/vscode/bin/test'
            displayName: 'Run tests'
            env:
              DISPLAY: :10 
          - task: PublishCodeCoverageResults@1
            inputs:
              codeCoverageTool: 'cobertura' # Options: cobertura, jaCoCo
              summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml
  - stage:
    displayName: "Publish extension"
    jobs:
      - job: "Publish"
        pool:
          name: Hosted Ubuntu 1604
          demands: npm
        steps:
          - task: Npm@1
            displayName: 'Install'
            inputs:
              command: install
          - task: Npm@1
            displayName: 'publish'
            inputs:
              command: custom
              customCommand: 'run publish -p $(TOKEN)'